### ISSUE TITLE
Nonce doesn't seem to work on Fedora 27

### ISSUE THREAD

**Issue by Mikerah** [Whiteblock/nonce#2]
System Info:
OS: Fedora 27
OS type: 64-bit
Processor: Intel Core i7

When trying to run `nonce` with 3 nodes using the lodestar dockerfile that @zscole made, I get the following error:
```
Removing Container 3...
Cleaning Networks
network0
-------------Building Node0 Network-------------
docker network create --subnet 10.1.0.0/16 --gateway 10.1.0.1 network0
de1f1f8088f29940259799b3f5924ad054e35b3eb6efaf082b26ae33426f5f57
10.1.0.0/30
10.1.0.1
1.35Building Node 0...
panic: Error response from daemon: invalid reference format

goroutine 1 [running]:
main.buildContainer(0x7fff572ecf26, 0x2b, 0x3)
	/home/mikerah/Documents/Projects/nonce/containers.go:51 +0x80b
main.main()
	/home/mikerah/Documents/Projects/nonce/main.go:31 +0x2fd
```

As per Zak's suggestion, I enabled the __experimental__ feature for docker-daemon and I still get the above error.

For reference, this is what I ran `./nonce -i ../blockchain-dockerfiles/ethereum/lodestar -n 3 -I wlp3s0
`

**Comment by n8wb** [comment]
You must build from an image using the -i flag not the dockerfile

**Comment by araskachoi** [comment]
Please make sure to take a look at the available flags by running `./nonce -h`.
But @n8wb is correct, please make sure you build the dockerfile into an image first
`docker build . -t  <image name>` then you will need to provide that <image name> into the -i flag

**Comment by Mikerah** [comment]
Hi @n8wb and @araskachoi,

I have been able to successfully nonce on my machine. 

Thanks
